### ISSUE TITLE
Not sure what's wrong

### ISSUE THREAD

**Issue by Listlessness** [polyfact/polyfact-js#78] opened 2023-10-02 03:04 UTC
import * as t from "polyfact-io-ts";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/runner/RapidHeartfeltOutliers/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

**Comment by Listlessness** [comment] 2023-10-02 03:05
/home/runner/RapidHeartfeltOutliers/node_modules/polyfact/index.js:1

**Comment by kevin-btc** [comment] 2023-10-02 08:46
Hi @Listlessness,

Thank you for reaching out and providing detailed information regarding the issue.

The error `SyntaxError: Cannot use import statement outside a module` usually indicates that the environment you're running the code in doesn't support ES6 module imports directly. This isn't an issue directly related to our SDK but more about how Node.js handles ES modules.

To resolve this, you can:

1. **Use CommonJS Syntax**: Instead of ES6 imports, you can use the `require` syntax:
   ```javascript
   const t = require("polyfact-io-ts");
   ```

2. **Enable ES6 Modules in Node.js**: If you're using a newer version of Node.js (v13.2.0 or later), you can use the ES6 import syntax by either:
   - Naming your file with a `.mjs` extension.
   - Or, adding `"type": "module"` in your `package.json` file.

3. **Use a Transpiler**: Tools like Babel can help you transpile your ES6 code to CommonJS, making it compatible with older versions of Node.js.

If you've already set up your project using the aforementioned approaches, there might be other configuration issues. We'd be happy to help further if you can share more details about your setup. 

Remember, while this isn't directly caused by our SDK, we aim to ensure our community has a smooth development experience, so don't hesitate to reach out with any further questions or concerns!

**Comment by lowczarc** [comment] 2023-10-02 08:49
Hey @Listlessness. Can you try to update to version 0.1.79 and confirm that it works ?
It seems there was an issue with our build system in nodejs

**Comment by lowczarc** [comment] 2023-10-04 11:00
Since it seems to be working on my side and someone else who had the same issue reported it being fixed on the discord, i'll close this issue.
Feel free to reopen it if the problem is still happening

**Closed by lowczarc** 2023-10-04 11:00 UTC
